// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Delete(arg1:number):Promise<void>;

export function ReadAll():Promise<Array<backend.Entry>>;

export function Write(arg1:string,arg2:backend.Format):Promise<void>;
