// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBytes() {
  return window['go']['backend']['App']['GetBytes']();
}

export function ReadAll() {
  return window['go']['backend']['App']['ReadAll']();
}

export function Write(arg1, arg2) {
  return window['go']['backend']['App']['Write'](arg1, arg2);
}
